# Generated by Django 2.0.3 on 2018-07-24 10:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
